### ISSUE TITLE
github action 没有触发

### ISSUE THREAD

**Issue by cocobear** [daixijun/ansible-role-mysql#1]
```
on:
  push:
    paths:
      - "*"
      - "!*.md"
      - "!.travis.yml"
```

修改了vars/main.yml文件， 按上面的规则应该会要触发github action的，但却没有。
如果改成
```
on: [push]
```
是可以触发的
